environment: dev

# Cluster configuration
clusterName: kafka-dev-cluster
kafkaVersion: 3.9.0
zookeeperReplicaCount: 1
brokerReplicaCount: 1
defaultReplicationFactor: 1
defaultMinInsyncReplicas: 1
interBrokerProtocolVersion: "3.9"
storage:
  brokerStorageSize: 20Gi
  zookeeperStorageSize: 20Gi
  class: divyam-managed-csi

broker_resources:
  cpu: 500m
  memory: 500Mi

zookeeper_resources:
  cpu: 200m
  memory: 200Mi

logs_topics:
  - name: router-metering-logs
    partitions: 1
    replicas: 1
    retentionMs: 2592000000  # 30 days
    retentionBytes: 2147483648 # 2 GB
    segmentBytes: 1073741824 # 1 GB
  - name: router-raw-logs
    partitions: 1
    replicas: 1
    retentionMs: 2592000000  # 30 days
    retentionBytes: 5368709120 # 5 GB
    segmentBytes: 1073741824 # 1 GB

connect_topics:
  configs:
    partitions: 1
    replicas: 1
    retentionMs: 2592000000  # 30 days
    retentionBytes: 100000000 # 100 MB
    segmentBytes: 10000000 # 10 MB

  offsets:
    partitions: 1
    replicas: 1
    retentionMs: 2592000000  # 30 days
    retentionBytes: 1073741824 # 1 GB
    segmentBytes: 1073741824 # 1 GB

  status:
    partitions: 1
    replicas: 1
    retentionMs: 2592000000  # 30 days
    retentionBytes: 1073741824 # 1 GB
    segmentBytes: 1073741824 # 1 GB

  dlq:
    partitions: 1
    replicas: 1
    retentionMs: 2592000000  # 30 days
    retentionBytes: 1073741824 # 1 GB
    segmentBytes: 1073741824 # 1 GB